命令稿啟動於 2018年03月 9日 下午 04:35:07
]0;~
[32mWei@DESKTOP-GKTJCOJ [33m~[0m
$ whoami;pwd
Wei
/cygdrive/c/Users/Wei/AppData/Roaming/SPB_Data
]0;~
[32mWei@DESKTOP-GKTJCOJ [33m~[0m
$ git config -l
use.email=wei831127@hotmail.com
user.email=wei831127@hotmail,com
user.name=fadedwei
]0;~
[32mWei@DESKTOP-GKTJCOJ [33m~[0m
$ git clone https://github.com/fadedwei/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 6, done.[K
remote: Compressing objects:  25% (1/4)   [Kremote: Compressing objects:  50% (2/4)   [Kremote: Compressing objects:  75% (3/4)   [Kremote: Compressing objects: 100% (4/4)   [Kremote: Compressing objects: 100% (4/4), done.[K
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  16% (1/6)   Unpacking objects:  33% (2/6)   Unpacking objects:  50% (3/6)   Unpacking objects:  66% (4/6)   Unpacking objects:  83% (5/6)   Unpacking objects: 100% (6/6)   Unpacking objects: 100% (6/6), done.
]0;~
[32mWei@DESKTOP-GKTJCOJ [33m~[0m
$ exit

命令稿已於 2018年03月 9日 下午 04:36:06
 完成